// Copyright 2025 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import * as path from 'path';
import * as vscode from 'vscode';
import {statNoThrow} from '../../../common/fs_util';

class OriginalFileCodeLens extends vscode.CodeLens {
  constructor(readonly originalFile: string) {
    super(new vscode.Range(0, 0, 0, 0), {
      title: 'Open original file',
      command: 'vscode.open',
      arguments: [vscode.Uri.file(originalFile)],
    });
  }
}

const GEN_PREPROCESSED_RE = /^out\/[^/]+\/gen\/(.*)\/preprocessed\/(.*)$/;

/**
 * Provides link to the original file on files generated by the build_webui rule.
 * https://source.chromium.org/chromium/chromium/src/+/main:ui/webui/resources/tools/build_webui.gni
 */
export class PreprocessedFilesCodeLensProvider
  implements vscode.CodeLensProvider<OriginalFileCodeLens>
{
  static documentSelector(srcDir: string): vscode.DocumentSelector {
    return [
      {
        scheme: 'file',
        // e.g. out/current_link/gen/chrome/browser/resources/extensions/preprocessed/service.ts
        pattern: `${srcDir}/out/*/gen/**/preprocessed/**`,
      },
    ];
  }

  static activate(srcDir: string): vscode.Disposable {
    return vscode.languages.registerCodeLensProvider(
      PreprocessedFilesCodeLensProvider.documentSelector(srcDir),
      new PreprocessedFilesCodeLensProvider(srcDir)
    );
  }

  constructor(private readonly srcDir: string) {}

  provideCodeLenses(
    document: vscode.TextDocument,
    _token: vscode.CancellationToken
  ): OriginalFileCodeLens[] {
    const m = GEN_PREPROCESSED_RE.exec(
      path.relative(this.srcDir, document.fileName)
    );
    if (!m) return [];
    const originalFile = path.join(this.srcDir, m[1], m[2]);
    return [new OriginalFileCodeLens(originalFile)];
  }

  async resolveCodeLens(
    lens: OriginalFileCodeLens,
    _token: vscode.CancellationToken
  ): Promise<OriginalFileCodeLens | undefined> {
    if (!(await statNoThrow(lens.originalFile))) return undefined;
    return lens;
  }
}
